"""insert user_id from category table

Revision ID: e49e859a73ad
Revises: 891898e7f57a
Create Date: 2026-05-24 17:07:31.564271

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e49e859a73ad'
down_revision: Union[str, Sequence[str], None] = '891898e7f57a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('user_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('categories_title_key'), 'categories', type_='unique')
    op.create_foreign_key(None, 'categories', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'categories', type_='foreignkey')
    op.create_unique_constraint(op.f('categories_title_key'), 'categories', ['title'], postgresql_nulls_not_distinct=False)
    op.drop_column('categories', 'user_id')
    # ### end Alembic commands ###
